# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c515a19b9a93fdce4ce7d499053843b0a519188c126880e0358df731f470a10c9c860d9242c0296ce7e8cac267d2d7c1299aa2a53f4ba30ddc64574521588b43

test:
  secret_key_base: 4554c8c472d763931b6d2c1aace94df1079a0f21a000a3dbc286130725b46c0fa8735554ef9a00d4a3e11fe478ccc4bec250fcbae7a70b282da0a8813b8e2b21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
